### ISSUE TITLE
unknown flag: --config-file

### ISSUE THREAD

**Issue by en666ki** [reugn/github-action-aerospike#2]
With following item:
```
- name: Set up Aerospike Database
        uses: reugn/github-action-aerospike@v1
        with:
          config-file: "./aerospike.conf"
          port: 3000
```
i am getting following error in ci
```
docker run -d --name gha_aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 -v /github/workspace/.:/opt/aerospike/etc --config-file /opt/aerospike/etc/aerospike.conf aerospike/aerospike-server:latest
unknown flag: --config-file
```

It looks like something bad with additional flags
